# on windows: mklink /d %userprofile%\.config %appdata%
[default.files]
# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#complex-target
# ".vimrc" = "~/.vimrc"
".vimrc" = { target = "~/.vimrc", type = "symbolic" }
".vim/after" = { target = "~/.vim/after", type = "symbolic" }

".config/bat/config" = "~/.config/bat/config"
".config/bottom/bottom.toml" = "~/.config/bottom/bottom.toml"
".config/helix" = "~/.config/helix"
".config/rhq/config.toml" = "~/.config/rhq/config.toml"
".config/gitui" = "~/.config/gitui"
".config/espanso/config" = "~/.config/espanso/config"
".config/espanso/match/base.yml" = { target = "~/.config/espanso/match/base.yml", type = "symbolic" }
