[[snippets]]
  description = "Get my IP adress"
  command = "curl ifconfig.io"
  output = ""

[[snippets]]
  description = "Watch files & reloading"
  command = "less +F"
  output = ""

[[snippets]]
  description = "日本語表示テスト"
  command = "echo 日本語表示テスト"
  output = ""

[[snippets]]
  description = "Heatseeker selection testing"
  command = "ls | hs"
  output = ""

[[snippets]]
  description = "Download file, named as a remote file name"
  command = "curl -O <URL>"
  output = ""

[[snippets]]
  description = "Unicode character to URL encode"
  command = "echo あ| nkf -wMQ | sd = %"
  output = ""

[[snippets]]
  description = "bat color redirect template"
  command = "bat --color=always -p justfile"
  output = ""

[[snippets]]
  description = "lolcat example (use seed)"
  command = "lolcat -s 130 justfile"
  output = ""

[[snippets]]
  description = "Create new Coreutils command's alias (windows)"
  command = "cd C:\\bat\\coreutils && echo @coreutils <name> %*> <name>.bat"
  output = ""

[[snippets]]
  description = "Teip example"
  command = "echo 100 200 300 400 500 | teip -f 2,4 -- lolcat -f -s 145"
  output = ""

[[snippets]]
  description = "Teip's more example"
  command = "echo 100 200 300 400 500 | teip -f 2,4 -- sd 0 000 | teip -f 2,4 -- lolcat -f -s 145"
  output = ""

[[snippets]]
  description = "cut example"
  command = "echo 100 200 300 400 500 | cut -f 1,3,5 -d \" \""
  output = ""

[[snippets]]
  description = "Teip moremore example"
  command = "seq -s \" \" 15 | teip -f 2,4,6,8,10,12,14 -- cmd /c \"sd .* 00000 | lolcat -s 140 -f\""
  output = ""

[[snippets]]
  description = "Listing systemdir exe commands (windows)"
  command = "cd C:\\Windows\\system32 & ls *.exe -1"
  output = ""

[[snippets]]
  description = "ripgrep windows filepath searching example"
  command = "rg -N --crlf %cd:\\=\\\\%$ \"%USERPROFILE%\\dirs.txt\""
  output = ""

[[snippets]]
  description = "Cargo command's list"
  command = "cargo --list"
  output = ""

[[snippets]]
  description = "Cargo tree (dependencies tree) example"
  command = "cd %USERPROFILE%\\rhq\\github.com\\ur0\\lolcat & cargo tree"
  output = ""

[[snippets]]
  description = "Hyperfine testing"
  command = "hyperfine \"type %USERPROFILE%\\dirs.txt\" \"bat %USERPROFILE%\\dirs.txt\" \"cat %USERPROFILE%\\dirs.txt\""
  output = ""

[[snippets]]
  description = "Watchexec example (saved time logging)"
  command = "watchexec -- echo Saved on: %time:~0,5%"
  output = ""

[[snippets]]
  description = "Teip csv example"
  command = "echo -e 1,aaa,Hoge team,yamada taro,2001\\n2,bbb,Super fuga team,ueda ryuchan,1998\\n3,ccc,N/A,toilet hanako,1998\\n | teip -d, -f 4"
  output = ""

[[snippets]]
  description = "Github search api result cache to json"
  command = "curl \"https://api.github.com/search/repositories?q=<Query>\" >> <Query>.json"
  output = ""

[[snippets]]
  description = "Check the Github API limit"
  command = "curl -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/rate_limit"
  output = ""

[[snippets]]
  description = "teip -s example"
  command = "echo ABCDEF | teip -s -og . -- rg [ABC]"
  output = ""

[[snippets]]
  description = "Rust binary size analyze per crate (with compile)"
  command = "cargo bloat --release --crates"
  output = ""

[[snippets]]
  description = "Insert space per any char"
  command = "echo <any char> | rg -o . | tr \\n \" \""
  output = ""
